### ISSUE TITLE
ghost goes under tile in B31

### ISSUE THREAD

**Issue by farling42** [MarkPearce/footsteps-of-otari-v10#10]
The ghost trail on level 2 goes under the tile in room B31.
Is it possible to put the ghost at a non-zero level so that it goes over the tile instead?

**Comment by MarkPearce** [comment]
Hmmm I don't think this is possible.  As the ghosts are drawn in directly in a pixi-layer.  If i get around to a version bump for v12 i'll look into it. (been a while!)

**Comment by farling42** [comment]
I haven't looked into pixi yet.
If it has its own layer, could this layer be created above the tiles layer?

I don't think the path of the ghost would ever pass through an area with an overhead tile.

**Comment by farling42** [comment]
It appears settings `ghostContainer.sortLayer = 710` after settings `ghostContainer.sort` will get it working.

Actually...

```
ghostContainer.sortLayer = PrimaryCanvasGroup.SORT_LAYERS.TOKENS
```

**Comment by MarkPearce** [comment]
Thanks for the fix!, added to latest release
