### ISSUE TITLE
Foundry complains that module is "unmaintained"

### ISSUE THREAD

**Issue by tianevitt** [MarkPearce/footsteps-of-otari-v10#8]
Hey there. I love this module, and I wanted to let you know that Foundry and the PF2E system are now complaining that it is "unmaintained".

Steps to reproduce:
Activate the module, and then load the game world

The following messages will appear in the console log:

![image](https://github.com/MarkPearce/footsteps-of-otari-v10/assets/89922402/d1c5b52a-8f84-40ea-8272-f69fd96c6c00)

It also puts a yellow banner at the top of the page when loading, so it is pretty loud about what amounts to a warning:

![image](https://github.com/MarkPearce/footsteps-of-otari-v10/assets/89922402/ee784d90-890e-4b87-b23b-afedec30128c)

I am sure that this is just a matter of bumping the verified version to 11 (which you probably know but what the heck; when I write bug reports, they are complete):

```
  "id": "footsteps-of-otari",
  "title": "Footsteps of Otari",
  "description": "Ghostly footprints and player handouts for The PF2e Abomination Vaults module",
  "version": "2.0.1",
  "compatibility": {
    "minimum": 10,
    "verified": 10
```
I have verified that the ghostly footprints still work on all three levels. 

(I am recommending this module in my own Otari-based modules, BTW, which are still a work in progress.)

Thanks!

**Comment by Meatbricks** [comment]
Hey tianevitt.
How did you get the ghostly footprints to work in v11?

**Comment by MarkPearce** [comment]
You can safely ignore the warning, it should work fine. You have an active scene right?

what problem are you experiencing?

**Comment by Meatbricks** [comment]
My mistake!
I had the scene open but not 'Active'.
As above. This is verified for FVTT V11.315 and Pf2e V5.136 I guess.
Thanks!

**Comment by tianevitt** [comment]
> Hey tianevitt. How did you get the ghostly footprints to work in v11?

Hey there. I don't recall doing anything special. I just made sure all maps were set to the proper version (original or new) and 
on the proper level, then I put the little ghost on the map and hit play. It worked perfectly!

I just was letting you know about that persistent message that foundry is being very loud about. So much overkill about a warning. I can ignore it.

**Comment by MarkPearce** [comment]
resolved... in 2.0.2.  did it take me a year to change one number? yes, yes it did.

**Comment by tianevitt** [comment]
And the warning is gone! Thanks. No worries at all; I have been sitting on changes to my own modules until after Foundry releases v12.
